### ISSUE TITLE
pLaTeX で JIS2004 字形にならない？

### ISSUE THREAD

**Issue by h20y6m** [zr-tex8r/PXjodel#1]
次のコマンドを実行し VF を生成し、
```
jfmutil jodel jlreq jlreq
jfmutil jodel jlreq-v jlreq
```
以下の文書を platex でタイプセットすると、
```tex
\documentclass[dvipdfmx]{jlreq}
\usepackage[prefix=jlreq,scale=1,deluxe,jis2004]{pxjodel}
\begin{document}
逢芦飴溢茨鰯淫迂厩噂餌襖迦牙廻恢晦蟹葛鞄釜翰翫徽
祇汲灸笈卿饗僅喰櫛屑粂祁隙倦捲牽鍵諺巷梗膏鵠甑叉
榊薩鯖錆鮫餐杓灼酋楯薯藷哨鞘杖蝕訊逗摺撰煎煽穿箭
詮噌遡揃遜腿蛸辿樽歎註瀦捗槌鎚辻挺鄭擢溺兎堵屠賭
瀞遁謎灘楢禰牌這秤駁箸叛挽誹樋稗逼謬豹廟瀕斧蔽瞥
蔑篇娩鞭庖蓬鱒迄儲餅籾爺鑓愈猷漣煉簾榔　冤叟咬嘲%屢
囀徘扁棘橙狡甕甦疼祟竈筵篝腱艘芒虔蜃蠅訝靄靱騙鴉
\end{document}
```
JIS2004 字形にならず JIS90 字形になります。
同様の事を uplatex で行った場合は JIS2004 字形になります。

**Comment by zr-tex8r** [comment]
原因がわかりました。

`jfmutil jodel`で採用しているVFの構成方法では
「hminrn-h（n付き）が2004JIS字形（つまりCMapが`2004-H`）である」
ことを前提にしていたはずなのに、途中でそれを失念していたようです。

恐らく、現状の「MAPFONTだけ置き換える」という方法では「前提」を外すことはできないと思われるので、結局、次のどちらかの方針を選ぶしかなさそうです。

1. その「前提」を仕様とする。つまり、pTeXで2004JIS字形を使いたいならば、DVIウェアのフォントマップを変える（hminrn-hのCMapを`2004-H`に変える）必要があることを明記する。
2. 「MAPFONTだけ置き換える」では無理なので「MAP自体を書き換える」（本来のjapanese-otfのVFのようにCIDのグリフに飛ばす）処理を組み込む。多分、入力のVFの性質に何か制限を加える必要が生じる。

もう少し検討してみます。

**Comment by h20y6m** [comment]
回答ありがとうございます。

> 「hminrn-h（n付き）が2004JIS字形（つまりCMapが`2004-H`）である」
> ことを前提にしていた

そういうことだったのですね。

自作パッケージ（https://github.com/h20y6m/jlreq-deluxe）では VF を自作する（つまり2の方法）ことでうまくいったので、expert用と同様の扱いなのかな？と思っていました。

（hminrn-h の CMap が `2004-H` ではなく `H` で VF で CID に飛ばしているのはやはり `2004-H` が標準の CMap ではないからだろうか？）

**Comment by zr-tex8r** [comment]
jfmutil（v1.3.1）と[pxjodel](https://github.com/zr-tex8r/PXjodel)（v0.3）の新版をリリースしました（TeX Live更新済み）。新版だと前掲の例は正しく2004JIS字形になるはずです。

---

「自分が欲しかったhminrn-h」に相当するもの、つまり
「2004JIS字形、JISコード、生（完全等幅）のメトリックのJFM」
をjodhminrn-hというVFで実装して、それをpxjodelの方に収録する、という解決法をとりました。この方法だと、当初想定した仕様を制限なく実現できるはずです。ファイルサイズの増加についても、pxjodelに追加したVFの分だけになり、`jfmutil jodel`で作ったVFのサイズはほぼ変わりません。

**Comment by zr-tex8r** [comment]
> hminrn-h の CMap が 2004-H ではなく H で VF で CID に飛ばしているのはやはり 2004-H が標準の CMap ではないからだろうか？

そうですね。2004-H/V のCMapはptex-fontmapsにおいて
「フォントマップを差し替えるだけで2004JIS字形に切り替わる」
ことを実現するために作成されたものです。

**Comment by h20y6m** [comment]
対応ありがとうございます。
こちらでも TeX Live の更新で正しく字形が切り替わることを確認しました。
